/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.*;
import java.awt.*;
import java.util.List;
import maths.MathsService;
import maths.QuizResult;

/**
 *
 * @author Aaron
 */
public class MathsSettingsPanel extends javax.swing.JPanel {

    private JFrame parent;
    private String selectedDifficulty = "Easy";
    private int selectedNumQuestions = 5;

    /**
     * Creates new form MathsPanel
     * 
     * @param parent
     */

    public MathsSettingsPanel() {
        initComponents();     
        setPreferredSize(new java.awt.Dimension(900, 600)); 
    }

   
    public MathsSettingsPanel(javax.swing.JFrame parent) {
        this();              
        this.parent = parent; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MathsPanelHeading = new javax.swing.JLabel();
        DiffLabel = new javax.swing.JLabel();
        DiffComboBox = new javax.swing.JComboBox<>();
        NumberOfQsLabel = new javax.swing.JLabel();
        QuestionsComboBox = new javax.swing.JComboBox<>();
        StartQuizButton = new javax.swing.JButton();
        ShowHistoryButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistoryPrintArea = new javax.swing.JTextArea();
        PastHistoryLabel = new javax.swing.JLabel();
        CloseButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        MathsPanelHeading.setBackground(new java.awt.Color(0, 0, 255));
        MathsPanelHeading.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        MathsPanelHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MathsPanelHeading.setText("Maths Section");

        DiffLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        DiffLabel.setText("Difficulty:");

        DiffComboBox.setBackground(new java.awt.Color(255, 153, 153));
        DiffComboBox.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        DiffComboBox.setMaximumRowCount(3);
        DiffComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Medium", "Hard", " " }));
        DiffComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DiffComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DiffComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiffComboBoxActionPerformed(evt);
            }
        });

        NumberOfQsLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        NumberOfQsLabel.setText("Number of Questions:");

        QuestionsComboBox.setBackground(new java.awt.Color(255, 255, 102));
        QuestionsComboBox.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        QuestionsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        QuestionsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionsComboBoxActionPerformed(evt);
            }
        });

        StartQuizButton.setBackground(new java.awt.Color(102, 255, 255));
        StartQuizButton.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        StartQuizButton.setText("Start Quiz");
        StartQuizButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        StartQuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartQuizButtonActionPerformed(evt);
            }
        });

        ShowHistoryButton.setBackground(new java.awt.Color(255, 153, 153));
        ShowHistoryButton.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        ShowHistoryButton.setText("Show History");
        ShowHistoryButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ShowHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowHistoryButtonActionPerformed(evt);
            }
        });

        HistoryPrintArea.setColumns(20);
        HistoryPrintArea.setRows(5);
        HistoryPrintArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 2, true));
        jScrollPane1.setViewportView(HistoryPrintArea);

        PastHistoryLabel.setBackground(new java.awt.Color(204, 204, 255));
        PastHistoryLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        PastHistoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PastHistoryLabel.setText("Past Quiz Results");

        CloseButton.setBackground(new java.awt.Color(255, 0, 0));
        CloseButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        CloseButton.setText("Close");
        CloseButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(0, 255, 255));
        BackButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MathsPanelHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NumberOfQsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(QuestionsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DiffLabel)
                        .addGap(18, 18, 18)
                        .addComponent(DiffComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StartQuizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ShowHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(PastHistoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MathsPanelHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiffLabel)
                    .addComponent(DiffComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberOfQsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuestionsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartQuizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(PastHistoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton)
                    .addComponent(CloseButton))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DiffComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiffComboBoxActionPerformed
       
    }//GEN-LAST:event_DiffComboBoxActionPerformed

    private void QuestionsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionsComboBoxActionPerformed
        
    }//GEN-LAST:event_QuestionsComboBoxActionPerformed

    private void StartQuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartQuizButtonActionPerformed
        
    }//GEN-LAST:event_StartQuizButtonActionPerformed

    private void ShowHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowHistoryButtonActionPerformed
        
    }//GEN-LAST:event_ShowHistoryButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        
    }//GEN-LAST:event_BackButtonActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CloseButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CloseButton;
    private javax.swing.JComboBox<String> DiffComboBox;
    private javax.swing.JLabel DiffLabel;
    private javax.swing.JTextArea HistoryPrintArea;
    private javax.swing.JLabel MathsPanelHeading;
    private javax.swing.JLabel NumberOfQsLabel;
    private javax.swing.JLabel PastHistoryLabel;
    private javax.swing.JComboBox<String> QuestionsComboBox;
    private javax.swing.JButton ShowHistoryButton;
    private javax.swing.JButton StartQuizButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
